### ISSUE TITLE
POS System - Faraha / Wary to share the device specifications

### ISSUE THREAD

**Issue by nanahamzah** [R-D-Theta-Edge/.github#137]
For GSPC paper

**Comment by farahaathirah24** [comment]
@nanahamzah @ridzuwary-theta-edge 
**Scanner Requirements**

- Type: 2D
- Connectivity: Bluetooth without adapter
- Compatibility: Tab connection
- Brand: No specified brand

**Suggested Tablets**
Additional Feature: NFC

- Xiaomi Pad 6 Max 14 
- Samsung Galaxy Tab Active5
- Lenovo Tab K11 Plus
- vivo Pad 
- vivo Pad2

**Comment by nanahamzah** [comment]
Faraha, additional feature NFC & Cellular Data kan?

**Comment by nanahamzah** [comment]
Emailed to Procurement. Task completed.

**Comment by nichleegc6929** [comment]
Received an email from Muhammad Khairul Aswan Bin Zamhari of Procurement team, 2nd Aug, 2.49pm:

Dear @Wan Nur Syazana Hanim Binti Wan Hamzah
 
Good day to you.
 
As per my RFQ from the vendors, email dated on 24th July 2024 (Wednesday) we already requested Lenovo Tab K11 Plus.
 
However, at this moment we only have received response from two (2) vendors, and they proposed different tablet model instead of Lenovo Tab K11 Plus.
 
Additionally, one of the vendors has replied us saying that the requested tablet not available in Malaysia.
 
Given the importance of acquiring the correct model for our needs, we would appreciate it if you can suggest other/additional potential vendors supplying this model or otherwise suggest new model of tablet.

**Comment by nichleegc6929** [comment]
Request @farahaathirah24 and @nanahamzah to revert on other brands to speed up the procurement of devices as we need to update the management (i.e. during GIWC) on the status of our bundling of POS system to market with our Sakupay partner, OgoShop.

**Comment by ThetaInno** [comment]
We attended the GSPC seating on September 30th, and the Committee has decided to hold the paper until next year. Their reasoning is that we can continue using the POS system / hardware provided by Ogoshop for our testing.
